### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jmpedrosa** [thetarnav/solid-devtools#187]
I've added to a context some complex objects, with no problem on execution. If try to expand the context, this exception is thrown

```
Uncaught RangeError: Maximum call stack size exceeded
    at R (solid-devtools.js?v=82d32e1d:1241:11)
    at solid-devtools.js?v=82d32e1d:1265:47
    at Array.map (<anonymous>)
    at R (solid-devtools.js?v=82d32e1d:1265:35)
    at R (solid-devtools.js?v=82d32e1d:1273:49)
    at solid-devtools.js?v=82d32e1d:1265:47
    at Array.map (<anonymous>)
    at R (solid-devtools.js?v=82d32e1d:1265:35)
    at R (solid-devtools.js?v=82d32e1d:1273:49)
    at solid-devtools.js?v=82d32e1d:1265:47
```

**Comment by thetarnav** [comment]
Thanks for reporting.
It would be great to see a simple reproduction of this. Just to roughly know when does it occur.
But to be honest I'm not too surprised. The serialization logic is not optimized right now so any larger object would overload the cpu unfortunately.

**Comment by jmpedrosa** [comment]
![image](https://user-images.githubusercontent.com/8169003/204100613-309f25f1-7ca5-4370-878b-b7361ab9437a.png)
![image](https://user-images.githubusercontent.com/8169003/204100642-9c15296c-bbbe-40f8-82ab-c8de84450a4a.png)
Exactly when you click on the arrow to expand the context.

**Comment by thetarnav** [comment]
Yeah I figured that much. Values aren't getting serialized deeply until they get inspected by clicking.
What I'm wondering is what about this object has caused this behavior. Is it its size that caused so many function calls to happen, or there is some problem with circular references that are resulting in an infinite loop.
This is why I would really appreciate a minimal reproduction or any addtional information about the data in the inspected object, so that I have a clear scenatio to test against.
But as I said, I'm already aware thet the system has flaws, so I'll be rewriting it anyway in the future.

**Comment by jmpedrosa** [comment]
@thetarnav I've tried to log the stringified object to console and the result was this:

```
Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'inputs' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    |     property 'children' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
    at Object.initModel
```
So yeah, circular references, infinite loop.
