### ISSUE TITLE
Locator tagetIDE does not work

### ISSUE THREAD

**Issue by mbarzeev** [thetarnav/solid-devtools#66]
I've configured the Locator well, making sure that the Babel transform plugin is set with jsxLocation to true - 
```javascript
plugins: [
        devtoolsPlugin({
            jsxLocation: true,
            name: true,
        }),
        solidPlugin(),
    ],
```
and in the main application I'm using the locator plugin, both with "vscode" and with a callback function, and both do not work.

```javascript
import {useLocatorPlugin} from 'solid-devtools';

useLocatorPlugin({
    targetIDE: 'vscode',
});
```

I see the highlight on my components in the page, with the component's name, but clicking it does nothing...
Also if I open and inspect the elements on the page I see that appended "data-source-loc" with the right data.
There are no console or extension's errors that I see.

Thanks.

**Comment by thetarnav** [comment]
Hey. Unfortunately, I'm not able to reproduce it. At least not exactly.
You have the latest version installed, right? (`0.10.1`)
What OS and browser?
On my windows, both chrome and firefox worked fine.
I have some issues with Opera though... It's a bit different because I can't even highlight the elements. But I'll have to look into it.
Not sure where the error might be, so you can try typing this in the console to see it `window.open` is even getting called when you click:
```ts
window.open = (...a) => {
    console.log("window.open", ...a)
}
```

**Comment by mbarzeev** [comment]
Hi,
Yeah I have version 0.10.1 and running on Ubuntu/Chrome.
Thing is that I don't even want the window to open anything, I just want to see the callback getting called :) Simply looks like the click event is not dispatched.
Pasting the code you've suggested, the `window.open` is not getting called.
Let me know if there is any more information I can provide.
Thanks!

**Comment by thetarnav** [comment]
I think that "Ubuntu" might be a keyword here.
I had this problem before, where the regex for reading data from the data-source-loc attribute wasn't working on macOS. I guess I forgot that mac isn't the only unix system...
If you install the newest locator package it *should* work. (`0.11.2`)
Tell me how it goes.

**Comment by mbarzeev** [comment]
Awesome! Now it works. Cheers 🍻

**Comment by thetarnav** [comment]
🎉🎉
